#Spring service的属性
server:
  port: 9014
  servlet:
    session:
      timeout: 30m

# Spring的系列的属性
spring:
  # 配置Spring服务的名称
  application:
    name: athena-cart
  #配置Spring resids的账户和连接
  redis:
    host: 192.168.25.137
    port: 6379
  # Springcloud alibaba nacos注册中心
  cloud:
    nacos:
      # 配置的Springcloud服务注册中心
      discovery:
        server-addr: 192.168.25.137:8848
  # 配置的时间输出格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  # 关闭thymeleaf的缓存
  thymeleaf:
    cache: false