#Spring service的属性
server:
  port: 9006
  servlet:
    session:
      timeout: 30m

# Spring的系列的属性
spring:
  # 配置Spring服务的名称
  application:
    name: athena-product
  #配置Spring datebase的账户和连接
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.25.137:32081/athena_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Springcloud alibaba nacos注册中心
  cloud:
    nacos:
      # 配置的Springcloud服务注册中心
      discovery:
        server-addr: 192.168.25.137:8848
    alicloud:
      access-key: LTAI5tEEw2Enr8eaZo2jd5j6
      secret-key: 3XdiJv6fCZ3XrrESMd4I58XZT83t2x
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
  # 配置的时间输出格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

# mybatis-plus的系列的属性
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  #设置实体类的自增主键
  global-config:
    db-config:
      id-type: auto
      #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0

# 日志数据输出
logging:
  level:
    com.zhuangxiaoyan.athena.product: debug