#Spring getway service的属性
server:
  port: 9010
  servlet:
    session:
      timeout: 30m

spring:
  #配置Spring服务的名称
  application:
    name: athena-getway
  cloud:
    nacos:
      # 配置的Springcloud服务注册中心
      discovery:
        server-addr: 192.168.25.137:8848
    gateway:
      routes:
        - id: athena-search-route
          uri: lb://athena-search
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        # high level athena-product service
        - id: athena-oss-route
          uri: lb://athena-oss
          predicates:
            - Path=/api/oss/policy/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        # high level athena-member service
        - id: athena-member-route
          uri: lb://athena-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        # high level athena-ware service
        - id: athena-ware-route
          uri: lb://athena-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        # high level athena-product service
        - id: athena-product-route
          uri: lb://athena-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        # high level athena-coupon service
        - id: athena-coupon-route
          uri: lb://athena-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        # low level athena-admin service
        - id: athena-admin-route
          uri: lb://athena-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /athena-admin/$\{segment}
        # low level athena-host-route service
        - id: athena-host-route
          uri: lb://athena-product
          predicates:
            - Host=athena.com,item.athena.com
        # low level athena-host-search service
        - id: athena-host-search
          uri: lb://athena-search
          predicates:
            - Host=search.athena.com



