#Spring getway service的属性
server:
  port: 9010
  servlet:
    session:
      timeout: 30m

spring:
  #配置Spring服务的名称
  application:
    name: athena-getway
  cloud:
    nacos:
      # 配置的Springcloud服务注册中心
      discovery:
        server-addr: 192.168.25.137:8848
    gateway:
      routes:
        # low level athena-admin service
        - id: athena-admin-route
          uri: lb://athena-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /athena-admin/$\{segment}
        # high level athena-product service
        - id: athena-product-route
          uri: lb://athena-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}
        # high level athena-product service
        - id: athena-coupon-route
          uri: lb://athena-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}






